export const ADD_LINER = "app/ADD_LINER";
export const ADD_LINERS = "app/ADD_LINERS";
export const ADD_LINERS_REQUEST = "app/ADD_LINERS_REQUEST";
export const ADD_AUTHOR_LINERS_REQUEST = "app/ADD_AUTHOR_LINERS_REQUEST";
export const ADD_AUTHORS_REQUEST = "app/ADD_AUTHORS_REQUEST";
export const ADD_LINER_REQUEST = "app/ADD_LINER_REQUEST";
