export const SET_LINERS_DATA = 'app/SET_LINERS_DATA';
export const SET_AUTHORS_DATA = 'app/SET_AUTHORS_DATA';
export const ADD_LINER = 'app/ADD_LINER';
export const ADD_NOTIFICATION = 'app/ADD_NOTIFICATION';
export const ADD_NOTIFICATION_REQUEST = 'app/ADD_NOTIFICATION_REQUEST';
export const DELETE_NOTIFICATION = 'app/DELETE_NOTIFICATION';
export const DELETE_NOTIFICATION_REQUEST = 'app/DELETE_NOTIFICATION_REQUEST';
export const REDUCER_NAME = 'app';
